- name: Preparing link create command
  ansible.builtin.set_fact:
    skupper_link_command:
      - skupper
      - link
      - create
      - --platform
      - "{{ platform }}"

- name: Adding --kubeconfig
  ansible.builtin.set_fact:
    skupper_link_command: "{{ skupper_link_command + ['--kubeconfig', kubeconfig] }}"
  when: kubeconfig is defined and kubeconfig | length() > 0

- name: Adding --context
  ansible.builtin.set_fact:
    skupper_link_command: "{{ skupper_link_command + ['--context', context] }}"
  when: context is defined and context | length() > 0

- name: Adding --namespace
  ansible.builtin.set_fact:
    skupper_link_command: "{{ skupper_link_command + ['--namespace', namespace] }}"
  when: namespace is defined and namespace | length() > 0
