---
# tasks file for skupper_init
- name: Kubernetes tasks
  ansible.builtin.include_tasks: kube-command.yml
  when: skupper_option_platform == 'kubernetes'
- name: Podman tasks
  ansible.builtin.include_tasks: podman-command.yml
  when: skupper_option_platform == 'podman'

# executing and validating result
- name: Executing skupper init
  ansible.builtin.command:
    argv: "{{ skupper_init_command }}"
  register: init_status
  changed_when: not init_status.failed
  failed_when: >
    init_status.failed and
    "Skupper has already been initialized" not in init_status.stderr_lines[0]

# load site info after initialization
- name: Loading site id
  skupper.skupper.site_load:
