argument_specs:
  main:
    short_description: Updates a Skupper site
    description: |
      Updates a Skupper site based on provided skupper options.
      For more information see L(skupper.skupper.skupper_option role,skupper_option_role.html).
    version_added: 1.6.0
    author: Skupper team
    options:
      skupper_update_force_restart:
        description: "Forces a restart of the Skupper components (applies only to kubernetes)"
        version_added: 1.6.0
        type: bool
        required: false
        default: false
      skupper_update_podman_timeout:
        description: "Timeout to use when updating a podman site (duration format)"
        version_added: 1.6.0
        type: str
        required: false
        default: "2m"
