---
- hosts: all
  tasks:
    - name: Creating the sample namespace
      kubernetes.core.k8s:
        kind: Namespace
        name: "{{ namespace }}"
        state: present
    - ansible.builtin.include_role:
        name: skupper.network.skupper_init
- hosts: sample-a
  tasks:
    - name: Removing secret
      kubernetes.core.k8s:
        kind: Secret
        name: "{{ token.name }}"
        namespace: "{{ namespace }}"
        state: absent
    - ansible.builtin.import_role:
        name: skupper.network.skupper_token
- hosts: sample-b
  tasks:
    - ansible.builtin.import_role:
        name: skupper.network.skupper_link
