---
- hosts: all
  tasks:
    - name: Removing namespace
      command: "kubectl delete namespace {{ skupper_option_namespace }}"
      register: out
      failed_when: out.failed and 'not found' not in out.stderr_lines[0]
