galaxy_info:
  author: Skupper team
  company: Red Hat
  description: Initializes a Skupper site
  issue_tracker_url: http://github.com/skupper/skupper
  license: Apache-2.0
  min_ansible_version: "2.1"
  platforms:
    - name: EL
    - name: Fedora
    - name: GenericLinux

  galaxy_tags:
    - skupper
    - init

dependencies:
  - role: skupper_option

# collections:
#   - kubernetes.core
