all:
  children:
    public:
      hosts:
        sample-a:
          ansible_connection: local
          skupper_option_namespace: sample-a
          skupper_token_name: sample-a-token
        sample-b:
          ansible_connection: local
          skupper_option_namespace: sample-b
          skupper_link_list:
            - host: sample-a
