---
- hosts: all
  collections:
    - skupper.skupper
  tasks:
    - import_role:
        name: skupper-link
      vars:
        skupper_link_links:
          - name: link1
            token: |
              your token as a YAML