---
# tasks file for skupper_update
- name: Kubernetes tasks
  ansible.builtin.include_tasks: kube-tasks.yml
  when: skupper_option_platform == 'kubernetes'
- name: Podman tasks
  ansible.builtin.include_tasks: podman-tasks.yml
  when: skupper_option_platform == 'podman'


# executing and validating result
- name: Executing skupper update
  ansible.builtin.command:
    argv: "{{ skupper_update_command }}"
  register: update_status
  changed_when: not update_status.failed
