---
- hosts: all
  tasks:
    - name: Updating service definitions
      ansible.builtin.import_role:
        name: skupper.network.skupper_service
      vars:
        skupper_option_namespace: sample
        skupper_service_services:
          sample-service:
            ports:
              - 8080
