---
- name: Prepare Kubernetes clusters
  hosts: kubernetes
  tasks:
    - name: Skupper V2 controller
      kubernetes.core.k8s:
        state: present
        src: https://raw.githubusercontent.com/skupperproject/skupper/refs/heads/v2/cmd/controller/deploy_cluster_scope.yaml

- name: Database deployment
  hosts: private-podman
  tasks:
    - name: Ensure that the podman.socket user scoped service is running and enabled
      ansible.builtin.systemd:
        name: podman.socket
        state: started
        enabled: true
        scope: user

    - name: Run the database container
      containers.podman.podman_container:
        name: database
        image: "{{ workload_image }}"
        state: started
        ports:
          - 5432:5432
        remove: true

- name: Set up the Skupper Network
  hosts: all
  tasks:
    - name: Creating Skupper resources
      fgiorgetti.skupperv2.resource:
        path: "{{ resources_path }}"
        namespace: "{{ namespace }}"
        platform: "{{ platform }}"

    - name: Issue a Skupper access token
      fgiorgetti.skupperv2.token:
        namespace: "{{ namespace }}"
        name: public-grant
        redemptionsAllowed: 2
      register: public_token
      when: inventory_hostname == 'public'

    - name: Saving access token to private sites
      fgiorgetti.skupperv2.resource:
        def: "{{ hostvars['public']['public_token']['token'] }}"
        state: latest
        namespace: "{{ namespace }}"
        platform: "{{ platform }}"
      when: inventory_hostname in groups['private']

    - name: System setup
      fgiorgetti.skupperv2.system:
        state: setup
      register: podman_out
      when: inventory_hostname == 'private-podman'

    - name: Create static link on private-kube
      fgiorgetti.skupperv2.resource:
        definition: "{{ hostvars['private-podman']['podman_out']['links']['host.minikube.internal'] }}"
        namespace: "{{ namespace }}"
        platform: "{{ platform }}"
      when: inventory_hostname == 'private-kube' and hostvars['private-podman']['podman_out']['links'] is defined
