---
- name: Teardown Kubernetes namespaces
  hosts: kubernetes
  tasks:
    - name: Delete the namespace
      kubernetes.core.k8s:
        state: absent
        kind: namespace
        name: "{{ namespace }}"
        wait: true

- name: Delete Podman site
  hosts: private-podman
  tasks:
    - name: Teardown site
      fgiorgetti.skupperv2.system:
        state: teardown

- name: Database removal
  hosts: private-podman
  tasks:
    - name: Delete the database container
      containers.podman.podman_container:
        name: database
        state: absent
