---
- name: Prepare Kubernetes clusters
  hosts: kubernetes
  tasks:
    - name: Skupper V2 controller
      kubernetes.core.k8s:
        state: present
        src: https://raw.githubusercontent.com/skupperproject/skupper/refs/heads/v2/cmd/controller/deploy_cluster_scope.yaml

- name: Database deployment
  hosts: private-podman
  tasks:
    - name: Ensure that the podman.socket user scoped service is running and enabled
      ansible.builtin.systemd:
        name: podman.socket
        state: started
        enabled: true
        scope: user

    - name: Run the database container
      containers.podman.podman_container:
        name: database
        image: "{{ workload_image }}"
        state: started
        ports:
          - 5432:5432
        remove: true

- name: Add Skupper Resources
  hosts: all
  tasks:
    - name: Creating Skupper resources
      fgiorgetti.skupperv2.resource:
        src: "{{ resources_path }}"
        namespace: "{{ namespace }}"
        platform: "{{ platform }}"

- name: Public token
  hosts: public
  tasks:
    - name: Issue a Skupper access token
      fgiorgetti.skupperv2.token:
        namespace: "{{ namespace }}"
      register: public_token

- name: Linking private sites to public
  hosts: private
  tasks:
    - name: Saving access token
      fgiorgetti.skupperv2.resource:
        definition: "{{ public_token.token }}"
        namespace: "{{ namespace }}"
        platform: "{{ platform }}"

- name: Initialize Podman site
  hosts: private-podman
  tasks:
    - name: System setup
      fgiorgetti.skupperv2.system:
        action: setup
      register: private_podman

- name: Linking private-kube to private-podman
  hosts: private-kube
  tasks:
    - name: Saving static link
      fgiorgetti.skupperv2.resource:
        definition: "{{ private_podman['links']['host.minikube.internal'] }}"
        namespace: "{{ namespace }}"
        platform: "{{ platform }}"
