---
- hosts: all
  collections:
    - skupper.network
  tasks:
    - import_role:
      name: skupper_token
    - name: Displaying generated tokens
      debug:
        msg: "Generated tokens -> {{ generated_token }}"
