---
# tasks file for skupper_teardown
- name: Kubernetes tasks
  ansible.builtin.include_tasks: kube-command.yml
  when: skupper_option_platform == 'kubernetes'
- name: Podman tasks
  ansible.builtin.include_tasks: podman-command.yml
  when: skupper_option_platform == 'podman'

# executing and validating result
- name: Executing skupper delete
  ansible.builtin.command:
    argv: "{{ skupper_teardown_command }}"
  register: delete_status
  changed_when: >
    not delete_status.failed and
    "Skupper is now removed " in delete_status.stdout_lines[0]
  failed_when: >
    delete_status.failed and
    "Skupper not installed in" not in delete_status.stderr_lines[0] and
    "Skupper is not enabled for" not in delete_status.stderr_lines[0]
