name: 
on:
  push:
    # Sequence of patterns matched against tags
    # Right now, we run this job automatically when a semantically versioned
    # tag is pushed (with an optional suffix).
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run ansible-lint
        uses: ansible-community/ansible-lint-action@main
        with:
          path: skupper/network --skip-list 'var-naming[pattern],var-naming[no-role-prefix]'
      - name: Ansible Publish
        uses: ansible/ansible-publish-action@v1.0.0
        with:
          api_key: ${{ secrets.ANSIBLE_API_KEY }}
          src_path: /github/workspace/skupper/network
