- name: Preparing service create command
  ansible.builtin.set_fact:
    skupper_create_command:
      - skupper
      - service
      - create
      - --platform
      - "{{ platform }}"

- name: Adding --kubeconfig
  ansible.builtin.set_fact:
    skupper_create_command: "{{ skupper_create_command + ['--kubeconfig', kubeconfig] }}"
  when: kubeconfig is defined and kubeconfig | length() > 0

- name: Adding --context
  ansible.builtin.set_fact:
    skupper_create_command: "{{ skupper_create_command + ['--context', context] }}"
  when: context is defined and context | length() > 0

- name: Adding --namespace
  ansible.builtin.set_fact:
    skupper_create_command: "{{ skupper_create_command + ['--namespace', namespace] }}"
  when: namespace is defined and namespace | length() > 0

- name: Execute skupper service create command
  ansible.builtin.include_tasks: service-create.yml
